### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by AsfandToor**
I have added Navbar. Its not responsive yet.

### CODE REVIEW

**Comment by Subhradeep10** [comment]
@AsfandToor Can you share the screenshot of your result

**Comment by AsfandToor** [comment]
I see you have merged it. Sorry for delay I couldn't respond.

**Comment by Subhradeep10** [comment]
@AsfandToor It's ok...but whenever if you make any PR, make sure you share the screenshot of your result.
Just giving a personal Advice

**Comment by Subhradeep10** [comment]
@AsfandToor Anyway you did a great work 🚀🚀

**Comment by AsfandToor** [comment]
I'll keep that in mind.

**Pull request merged**
